OnlineTestManager/OTM/ViewModels/TestTemplates/CreateTestTemplatesViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OTM.ViewModels.TestTemplates
{
    public class CreateTestTemplatesViewModel
    {
        [Display(Name = "Test Type")]
        public string TestTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<SelectListItem> TestTypes { get; set; }
    }
}

OnlineTestManager/OTM/ViewModels/TestTemplates/DeleteTestTemplateViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Data.Core.Domain;

namespace OTM.ViewModels.TestTemplates
{
    public class DeleteTestTemplateViewModel
    {
        public Guid Id { get; set; }    
        [Display(Name = "Test Type")]
        public string TestTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public TestType TestType { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

OnlineTestManager/OTM/ViewModels/TestTemplates/EditTestTemplatesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OTM.ViewModels.TestTemplates
{
    public class EditExercise
    {
        public Guid Id { get; set; }
        [Display(Name = "Exercises")]
        public string Description { get; set; }
    }

    public class EditTestTemplatesViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<EditExercise> Exercises { get; set; }
    }
}

OnlineTestManager/OTM/ViewModels/TestTemplates/IndexTestTemplatesViewModel.cs
using System;

namespace OTM.ViewModels.TestTemplates
{
    public class IndexTestTemplatesViewModel
    {
        public Guid Id { get; set; }
        public string TestTypeId { get; set; }
        public DateTime CreatedAt { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

OnlineTestManager/OTM/Controllers/ExerciseTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Constants;
using Microsoft.AspNetCore.Mvc;
using Data.Core.Domain;
using Data.Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using OTM.ViewModels.ExerciseTemplate;

namespace OTM.Controllers
{
    [Authorize(Roles = RoleConstants.TeacherRoleName)]
    [Route("[Controller]/[Action]")]
    public class ExerciseTemplatesController : Controller
    {
        private readonly IExercisesRepository _exercisesRepository;
        private readonly IAnswersRepository _answersRepository;
        private readonly IMapper _mapper;

        public ExerciseTemplatesController(IExercisesRepository exercisesRepository,
            IMapper mapper, IAnswersRepository answersRepository)
        {
            _exercisesRepository = exercisesRepository;
            _mapper = mapper;
            _answersRepository = answersRepository;
        }

        public IActionResult Create(Guid testTemplateId)
        {
            var createExeciseTemplatesViewModel = new CreateExerciseTemplatesViewModel {TestTemplateId = testTemplateId};

            return View(createExeciseTemplatesViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateExerciseTemplatesViewModel createExerciseTemplatesViewModel)
        {
            if (ModelState.IsValid)
            {
                var exercise = Exercise.Create(createExerciseTemplatesViewModel.Description,
                    createExerciseTemplatesViewModel.TestTemplateId);
                var insertedExercise = await _exercisesRepository.InsertAsync(exercise);

                return RedirectToAction(nameof(Create), "AnswerTemplates",
                    new {testTemplateId = createExerciseTemplatesViewModel.TestTemplateId, exerciseTemplateId = insertedExercise.Id});
            }
            
            return View(createExerciseTemplatesViewModel);
        }
        
        public async Task<IActionResult> Edit(Guid exerciseTemplateId, Guid testTemplateId)
        {
            var editExerciseTemplatesViewModel = new EditExerciseTemplatesViewModel
            {
                Id = exerciseTemplateId,
                TestTemplateId = testTemplateId
            };

            var exercise = await _exercisesRepository.GetByIdAsync(exerciseTemplateId);
            if (exercise == null)
            {
                return NotFound();
            }

            var answers = await  _answersRepository.GetAllAnswersOfExerciseAsync(exerciseTemplateId);
            if (answers == null)
            {
                return NotFound();
            }
            var editAnswer = _mapper.Map<List<EditAnswer>>(answers);

            editExerciseTemplatesViewModel.Answers = editAnswer;
            editExerciseTemplatesViewModel.Description = exercise.Description;

            return View(editExerciseTemplatesViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditExerciseTemplatesViewModel editExerciseTemplatesViewModel)
        {
            if (ModelState.IsValid)
            {
                var exercise = await _exercisesRepository.GetByIdAsync(editExerciseTemplatesViewModel.Id);

                if (exercise == null)
                {
                    return NotFound();
                }
                exercise.Update(editExerciseTemplatesViewModel.Description,
                    editExerciseTemplatesViewModel.TestTemplateId,false);
            
                await _exercisesRepository.UpdateAsync(exercise);

                return RedirectToAction(nameof(Edit), "TestTemplates",
                    new { id = editExerciseTemplatesViewModel.TestTemplateId});
            }
            
            return View(editExerciseTemplatesViewModel);
        }

        public IActionResult Delete(Guid exerciseTemplateId, Guid testTemplateId)
        {

            var exercise = _exercisesRepository.GetByIdAsync(exerciseTemplateId).Result;
            if (exercise == null)
            {
                return NotFound();
            }

            var deleteExerciseTemplatesViewModel = _mapper.Map<DeleteExerciseTemplateViewModel>(exercise);
            deleteExerciseTemplatesViewModel.TestTemplateId = testTemplateId;

            return View(deleteExerciseTemplatesViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DeleteExerciseTemplateViewModel deleteExerciseTemplatesViewModel)
        {
            var deletedExercice = await _exercisesRepository.DeleteAsync(deleteExerciseTemplatesViewModel.Id);
            if (!deletedExercice)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Edit),"TestTemplates", new {Id = deleteExerciseTemplatesViewModel.TestTemplateId});
        }
    }
}

OnlineTestManager/OTM/Controllers/TestTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Data.Core.Domain;
using Data.Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using OTM.UserContext;
using OTM.ViewModels.TestTemplates;


namespace OTM.Controllers
{
    [Authorize(Roles = RoleConstants.TeacherRoleName)]
    [Route("[Controller]/[Action]")]
    public class TestTemplatesController : Controller
    {
        private readonly ITestsRepository _testsRepository;
        private readonly IExercisesRepository _exercisesRepository;
        private readonly ITestTypesRepository _testTypesRepository;
        private readonly IMapper _mapper;
        private readonly Guid _userId;

        public TestTemplatesController(ITestsRepository testsRepository, IMapper mapper, 
            IUserContext userContext, 
            ITestTypesRepository testTypesRepository, 
            IExercisesRepository exercisesRepository)
        {
            _testsRepository = testsRepository;
            _mapper = mapper;
            _testTypesRepository = testTypesRepository;
            _exercisesRepository = exercisesRepository;

            var userId = userContext.GetLogedInUserId();
            if (userId == null)
            {
                throw new ApplicationException("userId is null");
            }
            _userId = (Guid)userId;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var testTemplates = _testsRepository.GetAllTestsOfTeacherAsync(_userId).Result;
            if (testTemplates == null)
            {
                return NotFound();
            }
                var indexTestTemplatesViewModel = _mapper.Map<IEnumerable<IndexTestTemplatesViewModel>>(testTemplates);
            return View(indexTestTemplatesViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var createTestTemplatesViewModel = new CreateTestTemplatesViewModel();
            var testTypes = new List<SelectListItem>();
            
            foreach (var testType in _testTypesRepository.GetAllAsync().Result)
            {
                testTypes.Add(new SelectListItem
                {
                    Value = testType.Id.ToString(),
                    Text = testType.Type
                });
            }
            
            createTestTemplatesViewModel.TestTypes = testTypes;
            return View(createTestTemplatesViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTestTemplatesViewModel createTestTemplatesViewModel)
        {
            if (!ModelState.IsValid)
                return View(createTestTemplatesViewModel);
            var testTemplateToCreate = Test.Create(createTestTemplatesViewModel.Name,
                createTestTemplatesViewModel.Description
                , _userId
                , Guid.Parse(createTestTemplatesViewModel.TestTypeId));
            var insertedTest = await _testsRepository.InsertAsync(testTemplateToCreate);

            return RedirectToAction(nameof(Edit), new {Id = insertedTest.Id});
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var test = _testsRepository.GetByIdAsync(id).Result;
            if (test == null)
            {
                return NotFound();
            }
            var editTestTemplatesViewModel = _mapper.Map<EditTestTemplatesViewModel>(test);

            var exercises = _exercisesRepository.GetAllExercisesOfTestAsync(id).Result;
            if (exercises == null)
            {
                return NotFound();
            }
            var editExercises = _mapper.Map<List<EditExercise>>(exercises);
            editTestTemplatesViewModel.Exercises = editExercises;

            return View(editTestTemplatesViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditTestTemplatesViewModel editTestTemplatesViewModel)
        {
            if (!ModelState.IsValid)
                return View(editTestTemplatesViewModel);

            var test = await _testsRepository.GetByIdAsync(editTestTemplatesViewModel.Id);
            if (test == null)
            {
                return NotFound();
            }
            test.Update(editTestTemplatesViewModel.Name, editTestTemplatesViewModel.Description, test.UserId, test.TestTypeId, false);
            await _testsRepository.UpdateAsync(test);                

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var test = _testsRepository.GetByIdAsync(id).Result;
            if (test == null)
            {
                return NotFound();
            }
            var deleteTestTemplateViewModel = _mapper.Map<DeleteTestTemplateViewModel>(test);

            return View(deleteTestTemplateViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(DeleteTestTemplateViewModel deteDeleteTestTemplateViewModel)
        {
            var deletedTest = await _testsRepository.DeleteAsync(deteDeleteTestTemplateViewModel.Id);
            if (!deletedTest)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineTestManager/OTM/Views/TestTemplates/Create.cshtml
@model OTM.ViewModels.TestTemplates.CreateTestTemplatesViewModel

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="box box-default" style="margin: 25px 0 0 0; text-align: center">


                <div class="box-header with-border">
                    <h3 class="box-title">Create a test template</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" asp-action="Create">
                    <div class="box-body">
                        
                        
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                <input asp-for="Name" class="form-control"/>
                            </div>

                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                <input asp-for="Description" class="form-control"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="TestTypeId" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                <select class="form-control select2-hidden-accessible" style="width: 100%;" tabindex="-1" aria-hidden="true" asp-for="TestTypeId" asp-items="@Model.TestTypes">
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <a class="btn btn-default" asp-action="Index" style="margin: 10px 0 10px 0">Cancel</a>
                            <button type="submit" class="btn btn-info">Create</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineTestManager/OTM/Views/TestTemplates/Delete.cshtml
@model OTM.ViewModels.TestTemplates.DeleteTestTemplateViewModel

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="box box-solid" style="margin: 25px 0 0 0;text-align: center">
                <div class="box-header with-border">
                    <h3 class="box-title">Test template details</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" asp-action="Delete">
                    <div class="box-body">
                        <div class="col-md-9">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Name)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Description)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Description)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedAt)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.CreatedAt)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.TestType)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.TestType.Type)
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer" style="text-align: center">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <a class="btn btn-default" asp-action="Index">Cancel</a>
                            <input type="submit" value="Delete" class="btn btn-info" />
                        </form>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </div>
</div>

OnlineTestManager/OTM/Views/TestTemplates/Details.cshtml
@model Data.Core.Domain.Test

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Test</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TestType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TestType.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

OnlineTestManager/OTM/Views/TestTemplates/Edit.cshtml
@model OTM.ViewModels.TestTemplates.EditTestTemplatesViewModel

<div class="content-wrapper">
    <div class="container-fluid">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="box box-solid" style="margin: 25px 0 0 0;text-align: center">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit current test template</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" asp-action="Edit">
                    <div class="box-body">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" asp-for="Id"/>
                        <div class="form-group">
                            <label asp-for="Name" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                <input asp-for="Name" class="form-control"/>
                            </div>

                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-2 control-label"></label>
                            <div class="col-sm-10">
                                <input asp-for="Description" class="form-control"/>
                            </div>
                            
                        </div>
                    </div>
                    <div class="box-footer" style="text-align: center">
                        <a class="btn btn-default pull-left" asp-action="Index">Cancel</a>
                        <a class="btn btn-default" asp-controller="ExerciseTemplates" asp-action="Create" asp-route-testTemplateId="@Model.Id">Add Exercise</a>
                        <button type="submit" class="btn btn-info pull-right">Save</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    
    <div class="container-fluid">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="box box-solid" style="margin: 25px 0 0 0;text-align: center">
                <div class="box-header with-border">
                    <h3 class="box-title">@Html.DisplayNameFor(model => model.Exercises) in this test template</h3>
                </div>
                @if (Model.Exercises.Count == 0)
                {
                    
                    /*<i class="fa fa-frown-o fa-5"></i>*/
                    <img src="~/dist/img/smiley_sad.png" style="padding: 15px" alt="Sad Images">
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                        No exercises currently in this test template.
                    </div>
                }
                <!-- /.box-header -->
                <!-- form start -->
                <table class="table">
                    <tbody>
                    @foreach (var item in Model.Exercises)
                    {
                        <tr>
                            <td style="padding: 15px 0 22px 0;font-size: 14px">
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default">Actions</button>
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a asp-controller="ExerciseTemplates" asp-action="Edit" asp-route-testTemplateId="@Model.Id" asp-route-exerciseTemplateId="@item.Id">Edit</a></li>
                                            <li><a asp-controller="ExerciseTemplates" asp-action="Delete" asp-route-testTemplateId="@Model.Id" asp-route-exerciseTemplateId="@item.Id">Delete</a></li>
                                        </ul>
                                    </div>
                                
                                
                                
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineTestManager/OTM/Views/TestTemplates/Index.cshtml
@model IEnumerable<OTM.ViewModels.TestTemplates.IndexTestTemplatesViewModel>

<div class="content-wrapper">
    <div class="container-fluid">

        <div class="col-md-3"></div>
        <div class="col-md-6" style="text-align: center">
            <a class="btn btn-info" asp-action="Create" style="margin: 10px 0 10px 0">Create New</a>

            @foreach (var item in Model)
            {
                <div class="box box-solid">
                    <div class="box-header with-border" style="text-align: center">
                        <i class="fa fa-file-text-o"></i>
                        <h3 class="box-title">@Html.DisplayFor(model => item.Name)</h3>

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="col-md-9">
                            <dl class="dl-horizontal">
                                <dt>Group @Html.DisplayNameFor(model => model.Description):</dt>
                                <dd>@Html.DisplayFor(modelItem => item.Description)</dd>
                                <dt>@Html.DisplayNameFor(model => model.CreatedAt):</dt>
                                <dd>@Html.DisplayFor(modelItem => item.CreatedAt)</dd>

                            </dl>
                        </div>
                        <div class="col-md-3">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default">Actions</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a asp-action="Edit" asp-route-id="@item.Id">Edit</a></li>
                                    <li><a asp-action="Delete" asp-route-id="@item.Id">Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-body -->
                </div>
            }
        </div>

    </div>
</div>