OnlineTestManager/OTM/Components/NavbarViewComponent.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Data.Core.Domain;
using Data.Core.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OTM.ViewModels;

namespace OTM.Components
{
    [ViewComponent(Name = "Navbar")]
    public class NavbarViewComponent : ViewComponent
    {
        private readonly IUsersRepository _usersRepository;
        private readonly string _userId;

        public NavbarViewComponent(IUsersRepository usersRepository, IHttpContextAccessor httpContextAccessor)
        {
            _usersRepository = usersRepository;

            _userId = httpContextAccessor.HttpContext.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            User user = null;

            if (_userId != null)
            {
                user = await _usersRepository.GetByIdAsync(Guid.Parse(_userId));
            }       

            var model = new NavbarViewModel()
            {
                Role = user?.UserRole.Role
            };

            return View(model);
        }
    }


}

OnlineTestManager/OTM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    @Html.Partial("Components/_Header")
</head>

<body class="hold-transition skin-blue sidebar-mini">
@await Component.InvokeAsync("Navbar")
<div class="wrapper">
    @RenderBody()
</div>
@Html.Partial("Components/_Footer")
@RenderSection("Scripts", required: false)
</body>
</html>